
language: python	
python:	
 - "3.5"	
cache: pip	
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter

script:	
 - source .
 - pytest --cov-report term-missing --cov=app 
 - coveralls
after_success:
 - coveralls
 - codeclimate-test-reporter
