
language: python

python:	
 - "3.5"	

cache: pip
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter

services:
  - postgresql
before_script:
  - psql -c "CREATE USER store_owner WITH PASSWORD 'password12345';" 
  - psql -c 'CREATE DATABASE store_manager_test owner store_owner;' 
  

script:	
 - pytest --cov-report term-missing --cov=app 
 - coveralls
 
after_success:
 - coveralls
 - codeclimate-test-reporter
